on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

defaults:
  run:
    shell: bash

jobs:
  danger:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install RubyGems
        run:
          bundle install --path=vendor/bundle
      - name: Run Danger
        run: |
          bundle exec danger

